name: Index Documents

on:
  push:
    branches:
      - main

jobs:
  index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run document indexing
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python index_documents.py --docs docs --storage ./storage

    - name: Upload indexed data
      uses: actions/upload-artifact@v3
      with:
        name: indexed-documents
        path: storage/
